name: Phonon
version: 0.1.0
sourceUrl: https://github.com/quark-dev/Phonon-Framework
homepageUrl: https://quark-dev.github.io/Phonon-Framework/
logo: favicon.png
icon: favicon.png
htmlHeader:
  - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
htmlBody:
  - <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  - <script>hljs.initHighlightingOnLoad();</script>
